blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('homepage.urls'), namespace='home')), 
    path('pages/', include(('posts.urls'), namespace='post')),    # namespace funciona si se define el nobmre de app, en el archivo urls.py de la App
    path('accounts/', include(('users.urls'), namespace='user'))    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # Para trabajar con imagenes

posts/urls.py
from django.urls import path
from .views import CategoryCreateView, CategoryListView, PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'post'

urlpatterns = [
    path('', PostListView.as_view(), name="list"),
    path('create/', PostCreateView.as_view(), name="create"),
    path('<int:pk>/', PostDetailView.as_view(), name="detail"),
    path('<int:pk>/update', PostUpdateView.as_view(), name="update"),
    path('<int:pk>/delete', PostDeleteView.as_view(), name="delete"),
    
    path('categoria/', CategoryCreateView.as_view(), name='categoria'),  
    path('listado_categoria/', CategoryListView.as_view(), name='list_categoria'),  
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import LoginFormView, PasswordEditView, ProfileEditView, UserRegisterView, UserEditView, ProfileDetailView

app_name = 'user'

urlpatterns = [
    path('signup/', UserRegisterView.as_view(), name='register'),
    path('login/', LoginFormView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('settings/', UserEditView.as_view(), name='edit_user'),
    path('settings/password', PasswordEditView.as_view(), name='change_password'),
    path('profile/<int:pk>/', ProfileDetailView.as_view(), name='detail_profile'),
    path('profile/<int:pk>/update', ProfileEditView.as_view(), name='edit_profile'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
class Category(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return f'{self.name}'

class Post(models.Model):
    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255)
    content = RichTextField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    content_image = models.ImageField(null=True, blank=True, upload_to='images/post/')
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # Eliminacion en cascada: Si se elimina un usuario se eliminan los Post relacionados a este.
    publish_date = models.DateTimeField(auto_now_add=True)  # Cuando se publica se agrega automaticamente la fecha actual
    last_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title + '|' + str(self.author)

posts/forms.py
from django import forms
from .models import Category, Post
class PostForm(forms.ModelForm):
     class Meta:
        model = Post
        fields = ('title', 'subtitle', 'category', 'content','content_image')
        widgets = {                                                        # Me permite utilizar bootstrap para el form
           'title': forms.TextInput(attrs={'class':'form-control'}),
           'subtitle': forms.TextInput(attrs={'class':'form-control'}),
           'category': forms.Select(attrs={'class':'form-control'}),
           'content': forms.Textarea(attrs={'class':'form-control'}),
           'content_image': forms.FileInput(attrs={'class':'form-control'}),
           
        }
        labels = {
           'title': 'Titulo',
           'subtitle': 'Subtitulo',
           'category': 'Categoria',
           'content': 'Contenido',
           'content_image': 'Imagen',
        }
class CategoryForm(forms.ModelForm):
     class Meta:
        model = Category
        fields = '__all__'
        widgets = {                                                        # Me permite utilizar bootstrap para el form
           'name': forms.TextInput(attrs={'class':'form-control'}),
        }
        labels = {
           'name': 'Nombre',
        }

posts/views.py
from .models import Category, Post
from .forms import  CategoryForm, PostForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
class PostListView(ListView):
    model = Post
    template_name = 'Posts/post_list.html'
    ordering = ['-id']

    def get_queryset(self):
        gq = Post.objects.all().order_by('-id')         # Los utlimos post se visualizaran primero
        post_a_buscar = self.request.GET.get('buscar')  # Necesito hacer referencia al nombre del input: 'buscar'!!
        if post_a_buscar:
            gq = gq.filter(title__icontains=post_a_buscar)
        return gq           

class PostDetailView(DetailView):
    model = Post
    template_name = 'Posts/post_detail.html'

class PostCreateView(LoginRequiredMixin, CreateView):
    # Por defecto CreateView y UpdateView toman como template: 'nombreModelo_form'
    model = Post
    form_class = PostForm
    template_name = 'Posts/postCreate_form.html'
    success_url = reverse_lazy('post:list')         # Para redirigir al usuario luego de crear un post --> Hace referencia al name que se asigna en posts/urls.py --> NO al nombre del template

    def form_valid(self, form):                     # Esto me permite asignar un Autor (usuario logueado) a un post, cuando este es creado
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm      
    template_name = 'Posts/postUpdate_form.html'                     
    success_url = reverse_lazy('post:list')  
class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    fields = '__all__'
    template_name = 'Posts/post_delete.html'        # DeleteView necesita una ventana de confirmacion para realizar la eliminacion
    success_url = reverse_lazy('post:list')

# ------------------------------------------------------
class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'Posts/categoria_create.html'
    success_url = reverse_lazy('post:list_categoria') 

class CategoryListView(ListView):
    model = Category
    template_name = 'Posts/categoria_list.html'

templates/Posts/categoria_create.html
{% extends 'Posts/post_list.html' %}

{% block title %}
Categorias
{% endblock title %}
{% block body_block%}

    <div class="container">
        <br>
        <h2>Crear Categoria</h2>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>

    </div>
{%endblock body_block%}

templates/Posts/categoria_list.html
{% extends 'Posts/post_list.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block body_block%}
    <br>
    <div class="container">
        <h2 class="mb-3">Listado de categorias</h2>
        {% if user.is_authenticated %}   
            <a class="btn btn-primary " href="{% url 'post:categoria' %}"><i class='fas fa-plus-circle' style='font-size:19px'></i> Crear nueva Categoria </a> 
            <br>
            <br>
        {% endif %}
            {% for categoria in object_list %}
                <ul>
                    <li>
                        <b>{{categoria}}</b>
                    </li>
            </ul>
            {% endfor %} 

    </div>
{%endblock body_block%}

templates/Posts/postCreate_form.html
{% extends 'Posts/post_list.html' %}

{% block title %}
    Post {{tipo_vista}}
{% endblock title %}

{% block body_block%}
    <br>
    <div class="container">
        {% if user.is_authenticated %}     {# Si intenta acceder por url (sin estar logeado) --> Redirecciona a login // Gracias a LOGIN_URL = '/accounts/login/' (Seteado en settings)#}
            <h2 class="mb-3">Crear Post</h2>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}
                <strong>{{form.as_p}}</strong>
                <div>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a class="btn btn-secondary" href="{% url 'post:list'%}"> Salir sin guardar </a>
                </div>
            </form>
        {% else %}
            <h2>Necesita permiso para acceder.</h2>
        {% endif %}   
    </div>

{%endblock body_block%}

templates/Posts/postUpdate_form.html
{% extends 'Posts/post_list.html' %}

{% block title %}
    Post {{tipo_vista}}
{% endblock title %}

{% block body_block%}
    <br>
    <div class="container">
            {% if user.id == post.author.id %}          {# Si el usuario que intenta acceder no coincide --> Msj de error#}
                <h2 class="mb-3">Actualizar Post</h2>                {# Si intenta acceder por url (sin estar logeado) --> Redirecciona a login // Gracias a LOGIN_URL = '/accounts/login/' (Seteado en settings)#}
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{form.media}}
                    <strong>{{form.as_p}}</strong>
                    <div>
                        <button type="submit" class="btn btn-primary">Guardar</button>
                        <a class="btn btn-secondary" href="{% url 'post:list'%}"> Salir sin guardar </a>
                    </div>
                </form>
            {% else %}
                <h2>Necesita permiso para acceder.</h2>
            {% endif %}
    </div>

{%endblock body_block%} 

templates/Posts/post_delete.html
{% extends 'Posts/post_list.html' %}
{% block title %}
    Post delate
{% endblock title %}

{% block body_block%}
    <br>
    <div class="container">
        {% if user.is_authenticated %}
            <h3 class="mb-3" style="text-align:center">¿Esta seguro que quiere eliminar el post: "{{post.title}}"?</h3>
            <form action="" method="post">
                {% csrf_token %}
                {{form}}
                <br>
                <div style="text-align:center">
                    <button type="submit" class="btn btn-danger">Eliminar <i class='fas fa-trash'></i></button>       
                    <a class="btn btn-primary" href="{% url 'post:list'%}"> Salir sin guardar </a>
                </div>
            </form>
        {% else %}
            <h2>Necesita permiso para acceder.</h2>
        {% endif %} 
    </div>

{%endblock body_block%}

templates/Posts/post_detail.html
{% extends 'Posts/post_list.html' %}
{% load static %}

{% block title %}
  Post {{post.id}}
{% endblock title %}

{% block body_block%}
    <br>
    <div class="container">  
        <div class="card">
            <div class="card-body">
                <h2>{{post.title}}</h2>
                <h4>{{post.subtitle}}</h4>
                <small> 
                    <b>@<a href={% url 'user:detail_profile' post.author.profile.id%} style="color:#000000">{{post.author}}</a> - {{post.publish_date|date:'d/m/Y'}} - {{post.category}}</b>
                </small>
                <hr>
                <div class="row">
                    <div class="col-md-auto">
                        {% if post.content_image %}
                            <img class="img-thumbnail" width="304" height="236" src="{{post.content_image.url}}">
                            <br>      
                            <br>      
                        {% endif %} 
                    </div>
                    <div class=" col-lg">
                        <br>
                        {{post.content|safe}}
                    </div>
                </div>
            </div>
        </div>
        <br>
            {% if user.id == post.author.id %}
            <a class="btn btn-primary" href={% url 'post:update' post.id %}>Modificar Post <i class='fas fa-pen'></i></a>
            <a class="btn btn-danger" href={% url 'post:delete' post.id %}>Eliminar Post <i class='fas fa-trash'></i></a>
            {% endif %}  
        <a class="btn btn-secondary" href={{request.META.HTTP_REFERER|escape}}>Volver</a>
    </div>
  
{%endblock body_block%}

templates/Posts/post_list.html
{% extends 'index.html' %}

{% block title %}
Posts
{% endblock title %}

{%block navbar_block%}
    <nav class="navbar navbar-expand-lg navbar-dark navbar-shrink" id="mainNav">   
{%endblock navbar_block%}

{% block body_block%}
    <br>
    <div class="container">
        <h2 class= "mb-3">Listado de posts</h2>
        <!-- Buscador y boton crear Posts -->   
        <div class="d-grid gap-2 d-md-flex">
            <div class="col-md-3 justify-content-md-between">
                <form class="d-flex" method="get">
                    <input class="form-control me-2" type="search" placeholder="Buscar" name="buscar"> 
                    <button class="btn btn-primary" type="submit"><i class="fas fa-search" style='font-size:19px'></i></button>
                </form>
            </div>
            {% if user.is_authenticated %}       
                <a class="btn btn-primary" href="{% url 'post:create' %}"><i class='fas fa-plus-circle' style='font-size:19px'></i> Crear nuevo Post </a> 
            {% endif %}
        </div>   

        <br>
        <!-- Tabla de Posts -->
        <table class="table table-striped table-bordered ">
            <thead class="thead-dark">
                <th scope="col">Titulo</th>
                <th scope="col">Usuario</th>
                <th scope="col">Categoria</th>
                <th scope="col">Fecha de Creacion</th>
                <th scope="col">Ultima actualizacion</th>
                <th scope="col">Acciones</th>
            </thead>
            <tbody>
                {% if post_list %}
                    {% for post in post_list  %}
                        <tr>
                            <td><strong>{{post.title}}</strong></td>
                            <td>{{post.author}}</td>
                            <td>{{post.category}}</td> 
                            <td>{{post.publish_date|date:'d/m/Y'}}</td>
                            <td>{{post.last_update|date:'d/m/Y H:i'}}</td>
                            <td>
                                <a class="btn btn-primary" href="{% url 'post:detail' post.id %}"> Ver detalle <i class='fas fa-eye'></i></a>
                                    {% if user.id == post.author.id %}
                                        <a class="btn btn-primary"  href="{% url 'post:update' post.id %}"> Editar <i class='fas fa-pen'></i></a>
                                        <a class="btn btn-danger"  href="{% url 'post:delete' post.id %}"> Eliminar <i class='fas fa-trash'></i></a>
                                    {% endif %}
                            </td>
                        </tr>
                {% endfor %} 
                {% else %}
                <h4>No hay registros de Posts</h4>
                <br>
                {% endif %}
            </tbody>
        </table>
    </div>

{%endblock body_block%}

{%block js_block%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script> 
{%endblock js_block%}