blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('homepage.urls'), namespace='home')), 
    path('pages/', include(('posts.urls'), namespace='post')),    # namespace funciona si se define el nobmre de app, en el archivo urls.py de la App
    path('accounts/', include(('users.urls'), namespace='user'))    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # Para trabajar con imagenes

homepage/urls.py
from django.urls import path
from .views import IndexView,AboutView

app_name = 'homepage'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
]

posts/urls.py
from django.urls import path
from .views import CategoryCreateView, CategoryListView, PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'post'

urlpatterns = [
    path('', PostListView.as_view(), name="list"),
    path('create/', PostCreateView.as_view(), name="create"),
    path('<int:pk>/', PostDetailView.as_view(), name="detail"),
    path('<int:pk>/update', PostUpdateView.as_view(), name="update"),
    path('<int:pk>/delete', PostDeleteView.as_view(), name="delete"),
    
    path('categoria/', CategoryCreateView.as_view(), name='categoria'),  
    path('listado_categoria/', CategoryListView.as_view(), name='list_categoria'),  
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import LoginFormView, PasswordEditView, ProfileEditView, UserRegisterView, UserEditView, ProfileDetailView

app_name = 'user'

urlpatterns = [
    path('signup/', UserRegisterView.as_view(), name='register'),
    path('login/', LoginFormView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('settings/', UserEditView.as_view(), name='edit_user'),
    path('settings/password', PasswordEditView.as_view(), name='change_password'),
    path('profile/<int:pk>/', ProfileDetailView.as_view(), name='detail_profile'),
    path('profile/<int:pk>/update', ProfileEditView.as_view(), name='edit_profile'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
class Category(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return f'{self.name}'

class Post(models.Model):
    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255)
    content = RichTextField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    content_image = models.ImageField(null=True, blank=True, upload_to='images/post/')
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # Eliminacion en cascada: Si se elimina un usuario se eliminan los Post relacionados a este.
    publish_date = models.DateTimeField(auto_now_add=True)  # Cuando se publica se agrega automaticamente la fecha actual
    last_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title + '|' + str(self.author)

templates/about.html
{% extends 'Posts/post_list.html' %}
{% load static %}
{% block title %}
About
{% endblock title %}

{%block navbar_block%}
    <nav class="navbar navbar-expand-lg navbar-dark navbar-shrink" id="mainNav">   
{%endblock navbar_block%}

{% block body_block%}
    <section class="page-section bg-light">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Developers</h2>
                <br>
            </div>
            <div class="row">
                <div class="col-lg-7">
                    <div class="team-member">
                        <img class="mx-auto rounded-circle" src={%static "img/team/27.jpg"%} alt="..." />
                        <h4>Elmer Estrada</h4>
                        <br>
                        <a class="btn btn-dark btn-social mx-2" href="mailto:elmerestrada27@gmail.com"><i class="fa fa-envelope"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href='https://www.linkedin.com/in/elmerestrada27'><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="team-member">
                        <img class="mx-auto rounded-circle" src={%static "img/team/28.jpeg"%} alt="..." />
                        <h4>Ezequiel Barletta Paz</h4>
                        <br>
                        <a class="btn btn-dark btn-social mx-2" href="mailto:ezequielbarletta@hotmail.com"><i class="fa fa-envelope"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://www.linkedin.com/in/ezequielbarlettapaz/"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
{%endblock body_block%}


{%block js_block%}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script> 
{%endblock js_block%}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title %}
            Tech Blog
            {% endblock title %}
        </title>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={%static 'css/styles.css'%} rel="stylesheet" />
        
        {% block block_head %}{% endblock block_head %}

        
    </head>
     <body id="page-top">
        <!-- Navbar -->
        {%block navbar_block%}
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top " id="mainNav">
        {%endblock navbar_block%}
            <div class="container">
                <a class="navbar-brand" href={%url 'homepage:index'%}><img src={%static "/img/iconhome.svg"%} alt="..." /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0"> 
                        <li class="nav-item"><a class="nav-link" href={% url 'post:list' %}>Posts</a></li>
                        <li class="nav-item"><a class="nav-link" href={% url 'post:list_categoria'%}>Categorias</a></li>
                        {% if not user.is_authenticated %}  
                            <li class="nav-item"><a class="nav-link" href={% url 'user:login' %}>Iniciar sesión</a></li>
                            <li class="nav-item"><a class="nav-link" href={% url 'user:register' %}>Registrarse</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link " href={%url 'homepage:about'%}>Acerca de mí</a></li>
                        {% if user.is_authenticated %}  
                            <li class="nav-item"><a class="nav-link" href={% url 'user:logout' %}>Cerrar sesión</a></li>
                            <li class="nav-item"><a class="nav-link" href={% url 'user:detail_profile' user.profile.id%}>@{{user.username}}</a></li>
                            {% if user.profile.avatar %}
                                <img class="rounded-circle border border-warning" src={{user.profile.avatar.url}} alt="..." height="38" width="38" />
                            {% else %}
                                <img class="rounded-circle border border-warning" src="{% static 'img/default_profile.svg' %}"alt="..." height="38" width="38" />                            
                            {% endif %}
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        {%block body_block%}

        <!-- Masthead-->
        <header class="masthead">
            <div class="container">
                <div class="masthead-subheading">Bienvenido!</div>
                <div class="masthead-heading text-uppercase">Tech Blog</div>
            </div>
        </header>
        <!-- Messages-->
        <div class="container text-center">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                        {{ message }}
                    </div>
                 {% endfor %}
            {% endif%}
         </div> 

        <!-- Publicaciones recientes-->
        <section class="page-section bg-light" id="portfolio">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">Publicaciones recientes</h2>
                    <br><hr><br>
                </div>

                <div class="row">
                    {% if ultimos_post %}
                        {% for post in ultimos_post  %}
                            <div class="col-lg-4 col-sm-6 mb-4 mb-sm-0-lg-0">
                                <div class="portfolio-item">
                                    <a class="portfolio-link" href={% url 'post:detail' post.id %}>
                                        <div class="portfolio-hover">
                                            <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                                        </div>
                                        {% if post.content_image %}
                                            <img class="card-img" src={{post.content_image.url}} alt="..." width="600" height="350"/>
                                        {% else %}
                                            <img class="card-img" src="{% static 'img/default_profile.svg' %}"alt="..." width="600" height="350"/>
                                        {% endif %}
                                    </a>
                                    <div class="portfolio-caption">
                                        <div class="portfolio-caption-heading">{{post.title}}</div>
                                        <div class="portfolio-caption-subheading text-muted">@{{post.author.username}}</div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %} 
                    {% else %}
                        <div class="text-center">
                            <h4>No hay registros de Posts</h4>
                            <br>
                        </div>
                    {% endif %}
                </div>
            </section>
        
        {%endblock body_block%}

        <!-- Footer-->
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    {% block footer_block%}
                        <div class="text-center">
                            - TECH BLOG -
                        </div> 
                    {% endblock footer_block %}
                </div>
            </div>
        </footer>
       

        {%block js_block%}
            <!-- Bootstrap core JS-->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
            <!-- Core theme JS-->
            <script src={%static "js/scripts.js"%}></script>
            <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script> 
        {%endblock js_block%}
    </body>
</html>