blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('homepage.urls'), namespace='home')), 
    path('pages/', include(('posts.urls'), namespace='post')),    # namespace funciona si se define el nobmre de app, en el archivo urls.py de la App
    path('accounts/', include(('users.urls'), namespace='user'))    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    # Para trabajar con imagenes

posts/urls.py
from django.urls import path
from .views import CategoryCreateView, CategoryListView, PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'post'

urlpatterns = [
    path('', PostListView.as_view(), name="list"),
    path('create/', PostCreateView.as_view(), name="create"),
    path('<int:pk>/', PostDetailView.as_view(), name="detail"),
    path('<int:pk>/update', PostUpdateView.as_view(), name="update"),
    path('<int:pk>/delete', PostDeleteView.as_view(), name="delete"),
    
    path('categoria/', CategoryCreateView.as_view(), name='categoria'),  
    path('listado_categoria/', CategoryListView.as_view(), name='list_categoria'),  
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import LoginFormView, PasswordEditView, ProfileEditView, UserRegisterView, UserEditView, ProfileDetailView

app_name = 'user'

urlpatterns = [
    path('signup/', UserRegisterView.as_view(), name='register'),
    path('login/', LoginFormView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('settings/', UserEditView.as_view(), name='edit_user'),
    path('settings/password', PasswordEditView.as_view(), name='change_password'),
    path('profile/<int:pk>/', ProfileDetailView.as_view(), name='detail_profile'),
    path('profile/<int:pk>/update', ProfileEditView.as_view(), name='edit_profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)  
    biography = RichTextField(blank=True, null=True)
    avatar = models.ImageField(null=True, blank=True, upload_to='images/profile/')
    website_url = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.user)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from .models import Profile

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']
    


class UserEditForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),           
            'first_name': forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={'class':'form-control'}),
        }
        
class ChangePasswordForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']
        widgets = {
                'old_password': forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}),
                'new_password1': forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}),
                'new_password2': forms.PasswordInput(attrs={'class':'form-control', 'type':'password'}),
            }    
class ProfileEditForm(forms.ModelForm):
        class Meta:
            model = Profile
            fields = ['biography','website_url','avatar']
            widgets = {
                'biography': forms.Textarea(attrs={'class':'form-control'}),
                'website_url': forms.TextInput(attrs={'class':'form-control'}),
                'avatar': forms.FileInput(attrs={'class':'form-control'}),
            }
            labels = {
            'biography': 'Biografía',
            'website_url': 'Página web',
            'avatar': 'Avatar',
            }

users/views.py
from django.shortcuts import get_object_or_404
from django.contrib.messages.views import SuccessMessageMixin
from django.views import generic
from posts.models import Post
from .forms import ChangePasswordForm, ProfileEditForm, UserEditForm, RegisterForm
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView, LoginView
from django.urls import reverse_lazy

class LoginFormView(SuccessMessageMixin, LoginView):
    template_name = 'Users/login.html'
    success_message = "Has iniciado sesión correctamente."

    def get_success_url(self):
        p, flag = Profile.objects.get_or_create(user=self.request.user, defaults={'id':self.request.user.id,'biography':"Mi biografía.."},)
        if flag:
            p.save()
        return super().get_success_url()
class UserRegisterView(SuccessMessageMixin, generic.CreateView):
    form_class = RegisterForm
    template_name = 'Users/user_register.html'
    success_url = reverse_lazy('user:login')
    success_message = "Su registro se ha realizado con éxito."

    def form_valid(self, form):
        response = super().form_valid(form)
        profile_create=Profile(user=self.object, biography="Mi biografía..")
        profile_create.save()
        return response
class UserEditView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    form_class = UserEditForm
    template_name = 'Users/edit_user.html'
    success_url = reverse_lazy('homepage:index')
    success_message = "Sus datos fueron actualizados correctamente."

    def get_object(self):
        return self.request.user

class PasswordEditView(SuccessMessageMixin, PasswordChangeView):
    form_class: ChangePasswordForm
    template_name='Users/change_password.html'
    success_url = reverse_lazy('homepage:index')
    success_message = "Has cambiado correctamente tu contraseña."
    
class ProfileDetailView(generic.DetailView):
    model = Profile
    template_name = 'Users/profile_detail.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        page_user = get_object_or_404(Profile, pk=self.kwargs['pk'])
        mis_posts = Post.objects.filter(author=page_user.user)
        context.update({'page_user':page_user, 'mis_posts':mis_posts})
        return context

class ProfileEditView(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    model = Profile
    form_class = ProfileEditForm
    template_name = 'Users/profile_edit.html'
    success_url = reverse_lazy('homepage:index')
    success_message = "Sus datos fueron actualizados correctamente."

templates/Users/change_password.html
{% extends 'Users/login.html' %}
{% load static %}

{% block title %}
    Perfil
{% endblock title %}

{% block body_block%}

    <body class="bg-light">
        <div class="container">
            <br><br><br>
            <br><br><br>
            <br><br><br>
            <div class="row">
                <div class="col-md-4 order-md-2 mb-4">
                    <br>
                    <br>
                    <img class="d-block mx-auto mb-4" src={%static "/img/user_register.svg"%} alt="" >
                </div>
        
                <div class="col-md-8 order-md-1">
                    <h1 class="mb-3">Cambiar contraseña</h1>
                    <hr>
                    <form method="post"%>
                        {% csrf_token %} 
                        <div class="mb-3">
                            <h6>Contraseña actual</h6>
                            <input type="password" class="form-control" name="old_password" required>
                        </div>
                        <div class="mb-3">
                            <h6>Nueva contraseña</h6>
                            <input type="password" class="form-control" name="new_password1" required>
                        </div>
                        <div class="mb-3">
                            <h6>Confirmar contraseña</h6>
                            <input type="password" class="form-control" name="new_password2" required>

                        </div>
                        <div class="py-4 text-center d-grid gap-2 col-5 mx-auto">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">Guardar</button>
                        </div>
                 
                        {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                {{ error.message }}
                                <div class="alert alert-danger">{{ error|escape }}</div>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                <div class="alert alert-danger">{{ error|escape }}</div>
                            {% endfor %}
                        {% endif %}
    

                    </form>
                </div>
            </div>
        </div>
    </body>

{%endblock body_block%}

templates/Users/edit_user.html
{% extends 'Users/login.html' %}
{% load static %}

{% block title %}
    Perfil
{% endblock title %}

{% block body_block%}

    <body class="bg-light">
        <div class="container">
            <br><br><br>
            <br><br><br>
            <br><br><br>
            <div class="row">
                <div class="col-md-4 order-md-2 mb-4">
                    <br>
                    <br>
                    <img class="d-block mx-auto mb-4" src={%static "/img/user_register.svg"%} alt="" >
                </div>

                <div class="col-md-8 order-md-1">
                    <h1 class="mb-3">Datos personales</h1>
                    <hr>
                    <form method="post" action="">
                        {% csrf_token %} 
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <h6>Nombre</h6>
                                {{form.first_name}}
                            </div>
                            <div class="col-md-6 mb-3">
                                <h6>Apellido</h6>
                                {{form.last_name}}
                            </div>
                        </div>

                        <div class="mb-3">
                            <h6>Username</h6>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">@</span>
                                </div>
                                {{form.username}}
                            </div>
                        </div>

                        <div class="mb-3">
                            <h6>Email</h6>
                            {{form.email}}
                        </div>

                        <div class="py-4 text-center d-grid gap-2 col-5 mx-auto">
                            <hr>
                            <button class="btn btn-primary btn-lg btn-block" type="submit"> Guardar datos </button>
                        </div>
                    </form>
                    <div class="text-center d-grid gap-2 col-5 mx-auto">
                        <hr>
                        <a class="btn btn-secondary btn-lg btn-block" href={% url 'user:change_password' %}>Cambiar contraseña</a>
                    </div>
                </div>
            </div>
        </div>
    </body>

{%endblock body_block%}

templates/Users/login.html
{% extends 'index.html' %}
{% load static %}

{% block title %}
    Iniciar sesión
{% endblock title %}

{% block block_head %}
    <link href={%static "css/signin.css"%} rel="stylesheet">
{% endblock block_head %}
    
{% block body_block%}
    <body class="text-center">   
        <br><br>
        <br><br>
        <br><br> 
        {% if messages %}
            <div class="container text-center" style="max-width: 350px">
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div> 
        {% endif%}
        <main class="form-signin">
        <form method="post" action="">
            {% csrf_token %} 
            <img class="mb-4" src={%static "img/login.svg"%} alt="" width="102" height="87">
            <h1>Iniciar Sesión</h1>
            <hr><br>
            <div class="form-floating">
                <input type="text" class="form-control" name="username" placeholder="Usuario" value="" required>
                <label for="floatingInput">Usuario</label>
            </div>
            <div class="form-floating">
                <input type="password" class="form-control" name="password" placeholder="Contraseña" value="" required>
                <label for="floatingPassword">Contraseña</label>
            </div>
            <br>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Ingresar </button>
        </form>
        <br>
            <a class="w-100 btn btn-lg btn-secondary" href={% url 'user:register' %}>Registrarse </a> 
            {% if form.errors %}
                <br><br>
                {% for field in form %}
                    {% for error in field.errors %}
                    {{ error.message }}
                    <div class="alert alert-danger">{{ error|escape }}</div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">{{ error|escape }}</div>
                {% endfor %}
            {% endif %} 
        </main>
    </body>

{% endblock body_block%}

{% block footer_block%}
    <!-- Footer-->
    <div class="text-center" style="color:#ffff">
        - TECH BLOG -
    </div>
{% endblock footer_block %}

templates/Users/profile_detail.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
    Perfil de usuario
{% endblock title %}

{%block navbar_block%}
    <nav class="navbar navbar-expand-lg navbar-dark navbar-shrink" id="mainNav">   
{%endblock navbar_block%}

{% block body_block%}
    <br>
    <div class="container">
        <div class="card mb-3">
            <div class="d-flex justify-content-between align-items-center mx-3 mt-3">
                <h2>Mi perfil</h2>
                <div class="btn-group" role="group">
                    {% if user.id == profile.user.id %}
                        <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Editar <i class="fas fa-user-edit"></i></button>
                        <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                        <li><a class="dropdown-item" href={% url 'user:edit_profile' page_user.user.id %}>Editar Perfil</a></li>
                        <li><a class="dropdown-item" href={% url 'user:edit_user'%}>Editar datos personales</a></li>
                        </ul>
                    {% endif %}
                </div>
            </div>
            
            <hr>
            <div class="row no-gutters">
                <div class="col-md-2">
                    <br>
                    {% if page_user.avatar %}
                            <img src="{{ page_user.avatar.url}}" class="card-img mx-3">                       
                    {% else %}
                        <img src="{% static 'img/default_profile.svg' %}" class="card-img mx-3">
                    {% endif %}
                </div>
                <div class="col-md-10 col-md-offset-2">
                    <div class="card-body">
                        <h5 class="card-title" >
                            {{ page_user.user.first_name }}
                            {{ page_user.user.last_name}}
                        </h5>
                        <p class="small text-muted">
                            {% if page_user.website_url %}
                                <a href="{{page_user.website_url}}">Website</a>
                            {% endif %} 
                        <p class="card-text">
                            {{ page_user.biography|safe }}
                            <br>
                            <div class="list-group" style="width: 500px">
                                <div class="list-group-item list-group-item-action active">
                                    <strong>Mis Posts: @{{ page_user.user.username }}</strong>
                                </div>
                                {% if mis_posts %}
                                    {% for post in mis_posts  %}
                                        <a class="list-group-item list-group-item-action" href="{% url 'post:detail' post.id %}"> <strong>{{post.title}}</strong>- {{post.category}} - {{post.publish_date|date:'d/m/Y'}} </a>
                                    {%endfor %}
                                {% else %}
                                    <a class="list-group-item list-group-item-action"> Sin posts registrados. </a>
                                {% endif %}
                              </div>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>    

{%endblock body_block%}

{%block js_block%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script> 
{%endblock js_block%}

templates/Users/profile_edit.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
    Perfil de usuario
{% endblock title %}

{%block navbar_block%}
    <nav class="navbar navbar-expand-lg navbar-dark navbar-shrink" id="mainNav">   
{%endblock navbar_block%}

{% block body_block%}

    <br>
    <div class="container">
        {% if user.id == profile.user.id %}          {# Si el usuario que intenta acceder no coincide --> Msj de error#}    
            <h2 class="mb-3">Actualizar Perfil</h2>                {# Si intenta acceder por url (sin estar logeado) --> Redirecciona a login // Gracias a LOGIN_URL = '/accounts/login/' (Seteado en settings)#}
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}
                <strong>{{form.as_p}}</strong>
                <div>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a class="btn btn-secondary" href="{% url 'user:detail_profile' user.profile.id%}"> Salir sin guardar </a>
                </div>
            </form>
        {% else %}
            <h2>Necesita permiso para acceder.</h2>
        {% endif %}

    </div>

{%endblock body_block%}

{%block js_block%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script> 
{%endblock js_block%}

templates/Users/user_register.html
{% extends 'Users/login.html' %}
{% load static %}

{% block title %}
    Registrarse
{% endblock title %}

{% block body_block%}

    <body class="bg-light">

        <div class="container">
            <br><br><br><br><br><br><br><br><br>
            <div class="row">
            <div class="col-md-4 order-md-2 mb-4">
                <br>
                <br>
                <img class="d-block mx-auto mb-4" src={%static "/img/user_register.svg"%} alt="" >
            </div>

            <div class="col-md-8 order-md-1">
                <h1 class="mb-3">Crea tu cuenta</h1>
                <hr>
                <form method="post" action="">
                    {% csrf_token %} 
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <h6>Nombre</h6>
                            <input type="text" class="form-control" name="first_name" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <h6>Apellido</h6>
                            <input type="text" class="form-control" name="last_name" required>
                        </div>
                    </div>

                    <div class="mb-3">
                        <h6>Username</h6>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">@</span>
                            </div>
                            <input type="text" class="form-control" name="username" placeholder="Username" required>
                        </div>
                    </div>

                    <div class="mb-3">
                        <h6>Email</h6>
                        <input type="email" class="form-control" name="email" placeholder="usuario@ejemplo.com" required>
                    </div>

                    <div class="mb-3 col-12">
                        <h6>Contraseña</h6>
                        <input type="password" class="form-control" name="password1" placeholder="" required>
                    </div>
        
                    <div class="col-12">
                        <h6>Repetir contraseña</h6>
                        <input type="password" class="form-control" name="password2" placeholder="" required>
                    </div>

                    <div class="py-4 text-center d-grid gap-2 col-5 mx-auto">
                        <hr>
                        <button class="btn btn-primary btn-lg btn-block" type="submit"> Registrarse </button>
                    </div>

                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                            {{ error.message }}
                            <div class="alert alert-danger">{{ error|escape }}</div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">{{ error|escape }}</div>
                        {% endfor %}
                    {% endif %}

                </form>
            </div>
        </div>
    </body>

{%endblock body_block%}